language: node_js
node_js:
  - 'stable'
  - '10'
  - '8'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache: yarn
script:
  - yarn codegen
  - yarn lint
  - yarn test
  - yarn build --release
